### ISSUE TITLE
Restrictive license prevents use

### ISSUE THREAD

**Issue by haight6716** [sikanrong/three-map-controls#5]
The GPLv3 is not intended for libraries.  It makes it impossible to use this library in any commercial closed-source project.  Maybe that's the intention.  Please consider re-licensing under the LGPL or similar.

**Comment by sikanrong** [comment]
hi there - will re-license soon. Sorry, been out of the game for a bit (a few months) but now I'm back.

**Comment by haight6716** [comment]
That's great news, thanks!

**Comment by alexburner** [comment]
+1, thanks @haight6716 and @sikanrong! Just curious, how soon is soon?

**Comment by sikanrong** [comment]
How soon is now? :dancing_men:

**Comment by sikanrong** [comment]
Alright the license has been updated and all changes have been released in version 0.11.5 of the NPM package. Good day to you sirs, and thanks for using my shit! Had no idea people cared about this library or its license, so very glad someone brought this to my attention

**Comment by haight6716** [comment]
@sikanrong thank you so much.  Have a look at it in use - we'll be releasing a new version with your code soon: https://www.extrahop.com/platform/7.0/

**Comment by alexburner** [comment]
(ﾉ^ヮ^)ﾉ*:・ﾟ✧

**Comment by jpwgarrison** [comment]
Thanks!!!
