### ISSUE TITLE
Rotate Camera

### ISSUE THREAD

**Issue by yahyavi** [sikanrong/three-map-controls#7]
Hi @sikanrong ,

I was wondering if there is support or you are planning on adding support for rotation?
I looked at the example and readme and didn't see anything.

Thanks!

**Comment by sikanrong** [comment]
Hey my dude! Rotation is not a use-case that I need for my application and so I really have no plans to support it, but you are very much invited to implement it and make a pull-request, so that it can be a part of this library! I would love that.

**Comment by yahyavi** [comment]
Cool, thanks for letting me know. I have to take care of some work stuff right now but if I get around to it I'd be happy to contribute.
